# this configuration file is available both in the frontend and the backend
# WARNING: never put any sensitive information in this file, as it is exposed to the client

# limit at which the content of a message will be truncated (UI and on the API)
truncation_limit: 10000
server_truncation_limit: 100000

# the name of this deployment instance (e.g. prod, local, preview, <custom name>)
instance_name: local

## authentication setup (Keycloak)

# realm name for authentication
authentication_realm: invariant-dev
# prefix of the client ID used to identify the authentication client (e.g. invariant- will be expanded to invariant-$APP_NAME)
authentication_client_id_prefix: invariant-dev

# whether this is a private instance or not (private instances do not offer a public homepage or any form of anonymous access)
private: false

# whether telemetry is enabled for this instance
telemetry: true
